spring.application.name=WORKER-SERVICE

server.port=8081
#spring.profiles.active=prod

# ===============================
# Database (MySQL)
# ===============================
# docker


#locally docker mysql run & SB locally
spring.datasource.url=jdbc:mysql://localhost:3306/construction

# Docker image run
#spring.datasource.url=jdbc:mysql://mysql-docker:3306/construction

spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60000

spring.cache.type=redis
spring.cache.redis.time-to-live=600000
spring.cache.redis.cache-null-values=false