spring:
  datasource:
    # Spring Boot running in Docker and MySQL container also in Docker
    url: jdbc:mysql://mysql-docker:3306/construction
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always