#spring:
#  datasource:
#docker DB Access
#    url: jdbc:mysql://localhost:3307/construction         # access in workbench using 3307 but pass data using 3306
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
