version: '3.8'
services:
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: rutwik
      MYSQL_PASSWORD: rutwik
      MYSQL_DATABASE: contructiondb_docker
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  spring-app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - mysql-db

volumes:
  mysql-data:
